baseURL = "https://dwalkr.github.io/sawmill/"
languageCode = "en-us"
theme = "sawmill"
title = "Sawmill"
[Author]
name = "DJ Walker"
[[menu.main]]
name = "Homepage"
url = "/"
weight = 4
[params]
logo = "/uploads/2018/05/19/amta-logo.png"
